"""empty message

Revision ID: 5ceca55a3e4a
Revises: 7a816d19b4ac
Create Date: 2017-03-05 19:54:33.170000

"""

# revision identifiers, used by Alembic.
revision = '5ceca55a3e4a'
down_revision = '7a816d19b4ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('icon', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'icon')
    ### end Alembic commands ###
