"""empty message

Revision ID: 7a816d19b4ac
Revises: 7c7868c9f819
Create Date: 2017-03-05 18:31:49.219000

"""

# revision identifiers, used by Alembic.
revision = '7a816d19b4ac'
down_revision = '7c7868c9f819'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('introduction', sa.String(length=512), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'introduction')
    ### end Alembic commands ###
