"""empty message

Revision ID: 9729a5e6229f
Revises: 218b8b2220e5
Create Date: 2017-02-28 20:49:22.196000

"""

# revision identifiers, used by Alembic.
revision = '9729a5e6229f'
down_revision = '218b8b2220e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('message_type', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'message_type')
    ### end Alembic commands ###
