"""empty message

Revision ID: c80dfa001703
Revises: 5ceca55a3e4a
Create Date: 2017-03-06 10:01:39.979000

"""

# revision identifiers, used by Alembic.
revision = 'c80dfa001703'
down_revision = '5ceca55a3e4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('web_index', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    ### end Alembic commands ###
